name: glad
description: glad
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.1
  open_file_safe_plus: ^0.0.3
  equatable: ^2.0.5
  get: ^4.6.5
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg:
  shimmer: ^2.0.0
  google_maps_flutter: ^2.2.2
  freezed_annotation: ^2.4.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts: ^22.2.7
  table_calendar: ^3.0.9
  expandable_text: ^2.3.0
  stepper_list_view: ^0.0.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.0.20
  geolocator: ^10.0.1
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  flutter_launcher_icons: ^0.13.1
  video_player: ^2.5.2
  video_thumbnail: ^0.5.3
  google_search_place: ^0.0.4
  device_info_plus: ^9.0.3

  intl: ^0.18.1
  location: ^5.0.0
  age_calculator: ^1.0.0
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^5.5.0
  youtube_player_flutter: ^8.1.2
  flutter_swipe_button: ^2.1.1+1
  like_button: ^2.0.5
  share_plus: ^7.2.1
  change_app_package_name: ^1.1.0
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  weather: ^3.1.1
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  info_popup: ^4.3.1
  grouped_list: ^5.1.2
  google_geocoding_api: ^1.4.1
  lite_rolling_switch: ^1.0.1
  visibility_detector: ^0.4.0+2
  currency_text_input_formatter: ^2.1.10
  talker_dio_logger: ^2.4.0
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/