name: glad
description: glad
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.0
  equatable: ^2.0.5
  get: ^4.6.5
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_svg:
  shimmer: ^2.0.0
  google_maps_flutter: ^2.2.2
  freezed_annotation: ^2.4.1
  geolocator: ^9.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/